export const DEMO_STUDENTS = [
  {
    id: 1,
    healthCondition: "Asthma Flare",
    rollNo: "8A01",
    name: "Aarav Sharma",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-04-15",
    bloodGroup: "O+",
    parent: { name: "Rajesh Sharma", contact: "+91-9876543210", email: "rajesh.s@example.com" },
    allergies: ["Dust"],
    medicalConditions: ["Mild Asthma"],
    vitals: { height: "155 cm", weight: "45 kg", bmi: 18.7, vision: "6/6", bloodPressure: "110/70" },
    vaccinations: [
      { name: "BCG", date: "2010-06-15", status: "completed" },
      { name: "OPV", date: "2010-08-20", status: "completed" },
      { name: "COVID-19", date: "2021-09-10", status: "completed" },
      { name: "MMR", date: "2011-04-05", status: "completed" },
    ],
    symptoms: ["Occasional cough"],
    reports: [{ date: "2024-01-15", type: "General Checkup", status: "Normal" }],
    aiSummary: "Aarav has a history of mild asthma triggered by dust. Vitals are stable. Keep inhaler handy.",
    perfectSummary: "Aarav should continue daily breathing exercises and carry his inhaler. Monitor seasonal dust exposure and ensure hydration during outdoor activities.",
    verifiedSymptoms: ["Occasional cough"],
    appointments: [
      {
        id: "appt-001",
        scheduledAt: "2024-08-02T10:30:00.000Z",
        status: "pending",
        consent: "pending",
        notes: "Follow-up asthma review with Dr. Rao.",
        createdBy: "doctor",
        createdAt: "2024-07-24T08:00:00.000Z",
      },
    ],
    medicalAchievements: ["Successfully completed asthma action plan"],
    medicalLeaveRequests: [
      {
        requestId: "leave-001",
        date: "2024-07-25",
        reason: "Rest day for respiratory recovery",
        status: "pending",
        approvedBy: "",
      },
    ],
    notifications: [
      { date: "2024-07-24", title: "Appointment proposed", message: "Dr. Rao proposed a follow-up visit on August 2.", type: "appointment", status: "pending" },
    ],
    risk: "observation",
    attendance: "96%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 2,
    healthCondition: "Healthy",
    rollNo: "8A02",
    name: "Diya Patel",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-07-22",
    bloodGroup: "A+",
    parent: { name: "Suresh Patel", contact: "+91-9876543211", email: "suresh.p@example.com" },
    allergies: ["Peanuts"],
    medicalConditions: ["None"],
    vitals: { height: "152 cm", weight: "42 kg", bmi: 18.2, vision: "6/9", bloodPressure: "105/65" },
    vaccinations: [
      { name: "BCG", date: "2010-09-22", status: "completed" },
      { name: "OPV", date: "2010-11-15", status: "completed" },
      { name: "COVID-19", date: "2021-10-05", status: "completed" },
      { name: "MMR", date: "2011-07-22", status: "completed" },
    ],
    symptoms: ["None"],
    reports: [{ date: "2024-02-10", type: "Eye Checkup", status: "Needs glasses" }],
    aiSummary: "Diya is healthy overall. Vision needs correction for mild myopia.",
    perfectSummary: "Diya is stable but needs regular eye exercises and an optometrist review for mild myopia. Keep classroom seating in the front row.",
    verifiedSymptoms: [],
    medicalAchievements: ["Adapted to corrective lenses successfully"],
    timeline: [
      { date: "2024-02-10", title: "Eye Checkup", description: "Mild myopia identified. Glasses recommended.", type: "report" },
      { date: "2024-03-03", title: "Follow-up", description: "Vision remains stable with glasses.", type: "checkin" },
    ],
    risk: "healthy",
    attendance: "98%",
    lastUpdate: "Yesterday",
    passportStatus: "Completed"
  },
  {
    id: 3,
    healthCondition: "Fever",
    rollNo: "8A03",
    name: "Arjun Kumar",
    class: "VIII-A",
    gender: "Male",
    dob: "2009-11-05",
    bloodGroup: "B+",
    parent: { name: "Vikram Kumar", contact: "+91-9876543212", email: "vikram.k@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "160 cm", weight: "50 kg", bmi: 19.5, vision: "6/6", bloodPressure: "115/75" },
    vaccinations: [
      { name: "BCG", date: "2010-01-05", status: "completed" },
      { name: "OPV", date: "2010-03-10", status: "completed" },
      { name: "COVID-19", date: "2021-11-20", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Fatigue"],
    reports: [{ date: "2024-03-05", type: "Blood Test", status: "Slight anemia" }],
    aiSummary: "Arjun shows signs of mild fatigue. Dietary adjustments recommended to boost iron levels.",
    risk: "review",
    attendance: "92%",
    lastUpdate: "2 days ago",
    passportStatus: "Completed"
  },
  {
    id: 4,
    healthCondition: "Healthy",
    rollNo: "8A04",
    name: "Sneha Reddy",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-02-14",
    bloodGroup: "AB+",
    parent: { name: "Kiran Reddy", contact: "+91-9876543213", email: "kiran.r@example.com" },
    allergies: ["Lactose Intolerant"],
    medicalConditions: ["None"],
    vitals: { height: "150 cm", weight: "40 kg", bmi: 17.8, vision: "6/6", bloodPressure: "100/60" },
    vaccinations: [
      { name: "BCG", date: "2010-04-14", status: "completed" },
      { name: "COVID-19", date: "2021-08-30", status: "completed" },
      { name: "MMR", date: "2011-02-14", status: "completed" },
      { name: "OPV", date: null, status: "pending" },
    ],
    symptoms: ["Stomach cramps occasionally"],
    reports: [],
    aiSummary: "Sneha is lactose intolerant. School cafeteria should be notified to avoid dairy products in meals.",
    risk: "healthy",
    attendance: "95%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 5,
    healthCondition: "Fever",
    rollNo: "8A05",
    name: "Rohan Singh",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-09-10",
    bloodGroup: "O-",
    parent: { name: "Amit Singh", contact: "+91-9876543214", email: "amit.s@example.com" },
    allergies: ["None"],
    medicalConditions: ["Type 1 Diabetes"],
    vitals: { height: "158 cm", weight: "52 kg", bmi: 20.8, vision: "6/6", bloodPressure: "112/70" },
    vaccinations: [
      { name: "BCG", date: "2010-11-10", status: "completed" },
      { name: "OPV", date: "2011-01-15", status: "completed" },
      { name: "COVID-19", date: "2021-07-22", status: "completed" },
      { name: "MMR", date: "2011-09-10", status: "completed" },
      { name: "Hepatitis B", date: "2010-12-05", status: "completed" },
    ],
    symptoms: ["Frequent thirst"],
    reports: [{ date: "2024-03-20", type: "Endocrinology", status: "HbA1c slightly elevated" }],
    aiSummary: "Rohan requires insulin monitoring during school hours. High priority observation for blood sugar levels.",
    perfectSummary: "Rohan must have insulin access and dietary supervision during school. Recommend a care plan meeting with parents and the school nurse.",
    verifiedSymptoms: ["Frequent thirst"],
    medicalAchievements: ["Completed diabetes management education program"],
    appointments: [
      {
        id: "appt-005",
        scheduledAt: "2024-08-05T14:00:00.000Z",
        status: "pending",
        consent: "pending",
        notes: "Diabetes follow-up with the pediatric endocrinology team.",
        createdBy: "doctor",
        createdAt: "2024-07-24T09:00:00.000Z",
      }
    ],
    risk: "critical",
    attendance: "85%",
    lastUpdate: "1 hour ago",
    passportStatus: "Pending"
  },
  {
    id: 6,
    healthCondition: "Healthy",
    rollNo: "8A06",
    name: "Ananya Iyer",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-01-25",
    bloodGroup: "B-",
    parent: { name: "Raman Iyer", contact: "+91-9876543215", email: "raman.i@example.com" },
    allergies: ["Pollen"],
    medicalConditions: ["None"],
    vitals: { height: "154 cm", weight: "44 kg", bmi: 18.5, vision: "6/6", bloodPressure: "108/68" },
    vaccinations: [
      { name: "BCG", date: "2010-03-25", status: "completed" },
      { name: "OPV", date: "2010-05-30", status: "completed" },
      { name: "COVID-19", date: "2021-09-15", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Sneezing"],
    reports: [{ date: "2023-11-10", type: "Allergy Test", status: "Pollen allergy confirmed" }],
    aiSummary: "Ananya experiences seasonal allergies. Provide antihistamines if symptoms flare up.",
    verifiedSymptoms: ["Sneezing"],
    medicalAchievements: ["Completed allergy management plan"],
    timeline: [
      { date: "2024-03-01", title: "Allergy Checkup", description: "Pollen sensitivity confirmed; antihistamine trial prescribed.", type: "report" },
    ],
    risk: "observation",
    attendance: "97%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 7,
    healthCondition: "Healthy",
    rollNo: "8A07",
    name: "Ishaan Verma",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-12-12",
    bloodGroup: "A-",
    parent: { name: "Deepak Verma", contact: "+91-9876543216", email: "deepak.v@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "157 cm", weight: "48 kg", bmi: 19.5, vision: "6/6", bloodPressure: "110/72" },
    vaccinations: [
      { name: "BCG", date: "2011-02-12", status: "completed" },
      { name: "OPV", date: "2011-04-18", status: "completed" },
      { name: "COVID-19", date: "2021-12-12", status: "completed" },
      { name: "MMR", date: "2012-01-05", status: "completed" },
    ],
    symptoms: ["None"],
    reports: [],
    aiSummary: "Ishaan is in excellent health. No current medical concerns.",
    risk: "healthy",
    attendance: "99%",
    lastUpdate: "Yesterday",
    passportStatus: "Completed"
  },
  {
    id: 8,
    healthCondition: "Healthy",
    rollNo: "8A08",
    name: "Kavya Menon",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-06-18",
    bloodGroup: "O+",
    parent: { name: "Prakash Menon", contact: "+91-9876543217", email: "prakash.m@example.com" },
    allergies: ["Soy"],
    medicalConditions: ["None"],
    vitals: { height: "153 cm", weight: "43 kg", bmi: 18.4, vision: "6/6", bloodPressure: "105/65" },
    vaccinations: [
      { name: "BCG", date: "2010-08-18", status: "completed" },
      { name: "OPV", date: "2010-10-22", status: "completed" },
      { name: "COVID-19", date: "2021-06-18", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Skin rash occasionally"],
    reports: [{ date: "2024-01-20", type: "Dermatology", status: "Mild dermatitis" }],
    aiSummary: "Kavya has mild contact dermatitis and soy allergy. Dietary restrictions needed.",
    risk: "observation",
    attendance: "94%",
    lastUpdate: "3 days ago",
    passportStatus: "Completed"
  },
  {
    id: 9,
    healthCondition: "Asthma Flare",
    rollNo: "8A09",
    name: "Aryan Gupta",
    class: "VIII-A",
    gender: "Male",
    dob: "2009-08-30",
    bloodGroup: "B+",
    parent: { name: "Sanjay Gupta", contact: "+91-9876543218", email: "sanjay.g@example.com" },
    allergies: ["None"],
    medicalConditions: ["Migraine"],
    vitals: { height: "162 cm", weight: "55 kg", bmi: 21.0, vision: "6/6", bloodPressure: "115/75" },
    vaccinations: [
      { name: "BCG", date: "2009-10-30", status: "completed" },
      { name: "OPV", date: "2009-12-15", status: "completed" },
      { name: "COVID-19", date: "2021-08-28", status: "completed" },
      { name: "MMR", date: "2010-08-30", status: "completed" },
    ],
    symptoms: ["Headache"],
    reports: [{ date: "2024-02-28", type: "Neurology", status: "Prescribed pain relievers" }],
    aiSummary: "Aryan suffers from occasional migraines. Needs a quiet space if an episode occurs.",
    risk: "review",
    attendance: "89%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 10,
    healthCondition: "Healthy",
    rollNo: "8A10",
    name: "Meera Nair",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-03-05",
    bloodGroup: "AB-",
    parent: { name: "Rajiv Nair", contact: "+91-9876543219", email: "rajiv.n@example.com" },
    allergies: ["Dust Mites"],
    medicalConditions: ["Asthma"],
    vitals: { height: "151 cm", weight: "41 kg", bmi: 18.0, vision: "6/12", bloodPressure: "102/62" },
    vaccinations: [
      { name: "BCG", date: "2010-05-05", status: "completed" },
      { name: "OPV", date: "2010-07-10", status: "completed" },
      { name: "COVID-19", date: "2021-03-05", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Wheezing"],
    reports: [{ date: "2024-04-01", type: "Pulmonology", status: "Moderate asthma control" }],
    aiSummary: "Meera requires an inhaler for asthma and wears corrective lenses. Keep away from dusty areas.",
    risk: "critical",
    attendance: "88%",
    lastUpdate: "Today",
    passportStatus: "Pending"
  },
  {
    id: 11,
    healthCondition: "Fever",
    rollNo: "8A11",
    name: "Aditya Desai",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-05-14",
    bloodGroup: "O+",
    parent: { name: "Kunal Desai", contact: "+91-9876543220", email: "kunal.d@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "159 cm", weight: "49 kg", bmi: 19.4, vision: "6/6", bloodPressure: "110/70" },
    vaccinations: [
      { name: "BCG", date: "2010-07-14", status: "completed" },
      { name: "OPV", date: "2010-09-20", status: "completed" },
      { name: "COVID-19", date: "2021-05-14", status: "completed" },
      { name: "MMR", date: "2011-05-14", status: "completed" },
    ],
    symptoms: ["None"],
    reports: [],
    aiSummary: "Aditya is generally healthy with stable vitals.",
    risk: "healthy",
    attendance: "96%",
    lastUpdate: "Yesterday",
    passportStatus: "Completed"
  },
  {
    id: 12,
    healthCondition: "Healthy",
    rollNo: "8A12",
    name: "Zara Khan",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-10-02",
    bloodGroup: "B+",
    parent: { name: "Imran Khan", contact: "+91-9876543221", email: "imran.k@example.com" },
    allergies: ["Penicillin"],
    medicalConditions: ["None"],
    vitals: { height: "156 cm", weight: "46 kg", bmi: 18.9, vision: "6/6", bloodPressure: "106/66" },
    vaccinations: [
      { name: "BCG", date: "2010-12-02", status: "completed" },
      { name: "OPV", date: "2011-02-08", status: "completed" },
      { name: "COVID-19", date: "2021-10-02", status: "completed" },
      { name: "MMR", date: "2011-10-02", status: "completed" },
    ],
    symptoms: ["None"],
    reports: [{ date: "2023-08-15", type: "Allergy Test", status: "Penicillin allergy noted" }],
    aiSummary: "Zara is healthy but has a strict penicillin allergy. Medical records must reflect this during emergencies.",
    risk: "observation",
    attendance: "98%",
    lastUpdate: "1 week ago",
    passportStatus: "Completed"
  },
  {
    id: 13,
    healthCondition: "Asthma Flare",
    rollNo: "8A13",
    name: "Vivaan Joshi",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-11-20",
    bloodGroup: "A+",
    parent: { name: "Anand Joshi", contact: "+91-9876543222", email: "anand.j@example.com" },
    allergies: ["None"],
    medicalConditions: ["Eczema"],
    vitals: { height: "155 cm", weight: "47 kg", bmi: 19.6, vision: "6/6", bloodPressure: "112/72" },
    vaccinations: [
      { name: "BCG", date: "2011-01-20", status: "completed" },
      { name: "OPV", date: "2011-03-25", status: "completed" },
      { name: "COVID-19", date: "2021-11-20", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Dry skin patches"],
    reports: [{ date: "2024-01-05", type: "Dermatology", status: "Topical cream prescribed" }],
    aiSummary: "Vivaan has mild eczema. Needs to apply moisturizer regularly, especially during winter.",
    risk: "observation",
    attendance: "95%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 14,
    healthCondition: "Fever",
    rollNo: "8A14",
    name: "Pooja Banerjee",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-08-08",
    bloodGroup: "O-",
    parent: { name: "Subhas Banerjee", contact: "+91-9876543223", email: "subhas.b@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "148 cm", weight: "38 kg", bmi: 17.3, vision: "6/6", bloodPressure: "98/60" },
    vaccinations: [
      { name: "BCG", date: "2010-10-08", status: "completed" },
      { name: "OPV", date: "2010-12-12", status: "completed" },
      { name: "COVID-19", date: "2021-08-08", status: "completed" },
      { name: "MMR", date: "2011-08-08", status: "completed" },
    ],
    symptoms: ["Low energy"],
    reports: [{ date: "2024-03-12", type: "Nutrition", status: "Underweight" }],
    aiSummary: "Pooja is slightly underweight. Nutritional counseling and a balanced diet are recommended.",
    risk: "review",
    attendance: "93%",
    lastUpdate: "Yesterday",
    passportStatus: "Pending"
  },
  {
    id: 15,
    healthCondition: "Healthy",
    rollNo: "8A15",
    name: "Krishna Pillai",
    class: "VIII-A",
    gender: "Male",
    dob: "2009-10-18",
    bloodGroup: "AB+",
    parent: { name: "Hari Pillai", contact: "+91-9876543224", email: "hari.p@example.com" },
    allergies: ["Shellfish"],
    medicalConditions: ["None"],
    vitals: { height: "165 cm", weight: "60 kg", bmi: 22.0, vision: "6/6", bloodPressure: "118/76" },
    vaccinations: [
      { name: "BCG", date: "2009-12-18", status: "completed" },
      { name: "OPV", date: "2010-02-22", status: "completed" },
      { name: "COVID-19", date: "2021-10-18", status: "completed" },
      { name: "MMR", date: "2010-10-18", status: "completed" },
    ],
    symptoms: ["None"],
    reports: [],
    aiSummary: "Krishna is healthy and athletic. Dietary restriction on shellfish must be noted.",
    risk: "healthy",
    attendance: "100%",
    lastUpdate: "2 days ago",
    passportStatus: "Completed"
  },
  {
    id: 16,
    healthCondition: "Healthy",
    rollNo: "8A16",
    name: "Sanya Malhotra",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-04-22",
    bloodGroup: "A-",
    parent: { name: "Rakesh Malhotra", contact: "+91-9876543225", email: "rakesh.m@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "154 cm", weight: "45 kg", bmi: 19.0, vision: "6/6", bloodPressure: "108/68" },
    vaccinations: [
      { name: "BCG", date: "2010-06-22", status: "completed" },
      { name: "OPV", date: "2010-08-28", status: "completed" },
      { name: "COVID-19", date: "2021-04-22", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["None"],
    reports: [],
    aiSummary: "Sanya has no significant medical conditions. Vitals are excellent.",
    risk: "healthy",
    attendance: "97%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 17,
    healthCondition: "Fever",
    rollNo: "8A17",
    name: "Dhruv Chauhan",
    class: "VIII-A",
    gender: "Male",
    dob: "2010-02-09",
    bloodGroup: "O+",
    parent: { name: "Mahesh Chauhan", contact: "+91-9876543226", email: "mahesh.c@example.com" },
    allergies: ["Tree Nuts"],
    medicalConditions: ["Hyperthyroidism"],
    vitals: { height: "160 cm", weight: "48 kg", bmi: 18.8, vision: "6/6", bloodPressure: "116/74" },
    vaccinations: [
      { name: "BCG", date: "2010-04-09", status: "completed" },
      { name: "OPV", date: "2010-06-14", status: "completed" },
      { name: "COVID-19", date: "2021-02-09", status: "completed" },
      { name: "MMR", date: "2011-02-09", status: "completed" },
    ],
    symptoms: ["Restlessness", "Weight loss"],
    reports: [{ date: "2024-03-30", type: "Endocrinology", status: "Thyroid levels irregular" }],
    aiSummary: "Dhruv is under medication for hyperthyroidism. Needs monitoring for restlessness and fatigue.",
    risk: "critical",
    attendance: "87%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  },
  {
    id: 18,
    healthCondition: "Healthy",
    rollNo: "8A18",
    name: "Neha Agarwal",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-05-28",
    bloodGroup: "B+",
    parent: { name: "Sunil Agarwal", contact: "+91-9876543227", email: "sunil.a@example.com" },
    allergies: ["None"],
    medicalConditions: ["Anemia"],
    vitals: { height: "150 cm", weight: "41 kg", bmi: 18.2, vision: "6/6", bloodPressure: "100/65" },
    vaccinations: [
      { name: "BCG", date: "2010-07-28", status: "completed" },
      { name: "OPV", date: "2010-09-02", status: "completed" },
      { name: "COVID-19", date: "2021-05-28", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Dizziness"],
    reports: [{ date: "2024-02-15", type: "Blood Test", status: "Low hemoglobin" }],
    aiSummary: "Neha has anemia. Needs iron supplements and should be excused from strenuous physical activities.",
    risk: "review",
    attendance: "91%",
    lastUpdate: "4 days ago",
    passportStatus: "Pending"
  },
  {
    id: 19,
    healthCondition: "Asthma Flare",
    rollNo: "8A19",
    name: "Aman Ahuja",
    class: "VIII-A",
    gender: "Male",
    dob: "2009-12-01",
    bloodGroup: "A+",
    parent: { name: "Gaurav Ahuja", contact: "+91-9876543228", email: "gaurav.a@example.com" },
    allergies: ["None"],
    medicalConditions: ["None"],
    vitals: { height: "158 cm", weight: "51 kg", bmi: 20.4, vision: "6/9", bloodPressure: "110/70" },
    vaccinations: [
      { name: "BCG", date: "2009-02-01", status: "completed" },
      { name: "OPV", date: "2009-04-06", status: "completed" },
      { name: "COVID-19", date: "2021-12-01", status: "completed" },
      { name: "MMR", date: "2010-12-01", status: "completed" },
    ],
    symptoms: ["Squinting"],
    reports: [{ date: "2024-01-10", type: "Eye Checkup", status: "Myopia detected" }],
    aiSummary: "Aman is healthy but needs to wear glasses for myopia during board work.",
    risk: "observation",
    attendance: "96%",
    lastUpdate: "Yesterday",
    passportStatus: "Completed"
  },
  {
    id: 20,
    healthCondition: "Healthy",
    rollNo: "8A20",
    name: "Ria Sengupta",
    class: "VIII-A",
    gender: "Female",
    dob: "2010-07-15",
    bloodGroup: "O+",
    parent: { name: "Anil Sengupta", contact: "+91-9876543229", email: "anil.s@example.com" },
    allergies: ["Gluten"],
    medicalConditions: ["Celiac Disease"],
    vitals: { height: "155 cm", weight: "45 kg", bmi: 18.7, vision: "6/6", bloodPressure: "105/68" },
    vaccinations: [
      { name: "BCG", date: "2010-09-15", status: "completed" },
      { name: "OPV", date: "2010-11-20", status: "completed" },
      { name: "COVID-19", date: "2021-07-15", status: "completed" },
      { name: "MMR", date: null, status: "pending" },
    ],
    symptoms: ["Bloating occasionally"],
    reports: [{ date: "2023-09-20", type: "Gastroenterology", status: "Celiac confirmed" }],
    aiSummary: "Ria has celiac disease. Requires a strict gluten-free diet in the school premises.",
    risk: "review",
    attendance: "94%",
    lastUpdate: "Today",
    passportStatus: "Completed"
  }
];